version: 0.2

env:
  shell: bash
  variables:
    SAM_CLI_LINK: 'https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip'
    SAM_CLI_PACKAGE_NAME: 'aws-sam-cli.zip'

phases:
  install:
    run-as: root
    on-failure: ABORT
    runtime-versions:
      python: 3.12
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - yum install -y unzip
      - wget -qO "${SAM_CLI_PACKAGE_NAME}" "${SAM_CLI_LINK}"
      - unzip -qq "${SAM_CLI_PACKAGE_NAME}" -d sam-installation
      - ./sam-installation/install
      - sam --version
  build:
    on-failure: ABORT
    commands:
      - sam build
      - sam deploy --image-repository 823598220965.dkr.ecr.eu-west-1.amazonaws.com/sam --stack-name lambda-function-html-to-pdf-printer-stage --capabilities CAPABILITY_NAMED_IAM --fail-on-empty-changeset false --no-confirm-changeset