version: 0.2

#env:
#  shell: bash
#  variables:
#    SAM_CLI_LINK: 'https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip'
#    SAM_CLI_PACKAGE_NAME: 'aws-sam-cli.zip'

phases:
  install:
    run-as: root
    on-failure: ABORT
    runtime-versions:
      python: 3.12
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    on-failure: ABORT
    commands:
      - |
        aws ecr get-login-password --region $AWS_DEFAULT_REGION \
        | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    on-failure: ABORT
    commands:
      - EPOCH_TAG=$(date +%s)
      - IMAGE_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${SERVICE_NAME}-${ENVIRONMENT}
      - docker build . -t "${SERVICE_NAME}-${ENVIRONMENT}"
      - |
        docker tag "${SERVICE_NAME}-${ENVIRONMENT}:latest" \
        "${IMAGE_URI}:latest"
      - |
        docker tag "${SERVICE_NAME}-${ENVIRONMENT}:latest" \
        "${IMAGE_URI}:${EPOCH_TAG}"
      - docker push "${IMAGE_URI}" --all-tags
      - ACTUAL_TASK_DEFINITION_ARN=$(aws ssm get-parameter --name "/ecs/task-definitions/${SERVICE_NAME}/${ENVIRONMENT}/arn" --query "Parameter.Value" --output text)
      - echo "Actual task definition: ${ACTUAL_TASK_DEFINITION_ARN}"
      - |
        aws cloudformation update-stack --stack-name ${ENVIRONMENT}-${SERVICE_NAME}-task-definition \
        --parameters ParameterKey=ImageTag,ParameterValue=${EPOCH_TAG} \
        ParameterKey=Cpu,UsePreviousValue=true \
        ParameterKey=Memory,UsePreviousValue=true \
        ParameterKey=ContainerName,UsePreviousValue=true \
        ParameterKey=ContainerPort,UsePreviousValue=true \
        ParameterKey=Environment,UsePreviousValue=true \
        ParameterKey=EFSMountPath,UsePreviousValue=true \
        ParameterKey=Registry,UsePreviousValue=true \
        ParameterKey=ServiceName,UsePreviousValue=true \
        ParameterKey=ImageName,UsePreviousValue=true \
        ParameterKey=EFSFileSystemId,UsePreviousValue=true \
        --capabilities CAPABILITY_IAM \
        --use-previous-template
