services:
  app:
    build:
      args:
        DEV: true
        EFS_MOUNT_PATH: /test
      target: builder
    ports:
      - "5000:5000"
    volumes:
      - ./src:/src
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    entrypoint: [ "/src/entrypoint.dev.sh" ]