services:
  app:
    build:
      target: develop
    ports:
      - "5000:5000"
    volumes:
      - ./src:/src
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    entrypoint: [ "/src/entrypoint.dev.sh" ]